/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiuser;

import com.sun.glass.events.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Balreira 07 Jan 2019
 */
public class EscolherZona extends javax.swing.JFrame {
    

    /**
     * Creates new form VerParques
     */
    public EscolherZona() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Zonas = new javax.swing.JLabel();
        Oeste = new javax.swing.JButton();
        Centro = new javax.swing.JButton();
        Este = new javax.swing.JButton();
        Sul = new javax.swing.JButton();
        Norte = new javax.swing.JButton();
        Voltar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Zonas.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        Zonas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Zonas.setText("Zonas");
        Zonas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Zonas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Zonas.setVerifyInputWhenFocusTarget(false);

        Oeste.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Oeste.setText("Oeste");
        Oeste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OesteActionPerformed(evt);
            }
        });
        Oeste.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OesteKeyPressed(evt);
            }
        });

        Centro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Centro.setText("Centro");
        Centro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CentroActionPerformed(evt);
            }
        });
        Centro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CentroKeyPressed(evt);
            }
        });

        Este.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Este.setText("Este");
        Este.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EsteActionPerformed(evt);
            }
        });
        Este.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                EsteKeyPressed(evt);
            }
        });

        Sul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sul.setText("Sul");
        Sul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SulActionPerformed(evt);
            }
        });
        Sul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SulKeyPressed(evt);
            }
        });

        Norte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Norte.setText("Norte");
        Norte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Norte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NorteActionPerformed(evt);
            }
        });
        Norte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NorteKeyPressed(evt);
            }
        });

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        Voltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VoltarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Oeste, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Centro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Norte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(Este, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Voltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Zonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Zonas)
                .addGap(27, 27, 27)
                .addComponent(Norte)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Este)
                    .addComponent(Centro)
                    .addComponent(Oeste))
                .addGap(53, 53, 53)
                .addComponent(Sul)
                .addGap(11, 11, 11)
                .addComponent(Voltar)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Centro, Este});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CentroActionPerformed
        try {
            VerParques v = new VerParques('c');
            v.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(EscolherZona.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_CentroActionPerformed

    private void NorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NorteActionPerformed
        try {
            VerParques v = new VerParques('n');
            v.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(EscolherZona.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_NorteActionPerformed

    private void OesteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OesteActionPerformed
        try {
            VerParques v = new VerParques('o');
            v.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(EscolherZona.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_OesteActionPerformed

    private void EsteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EsteActionPerformed
        try {
            VerParques v = new VerParques('e');
            v.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(EscolherZona.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_EsteActionPerformed

    private void SulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SulActionPerformed
        try {
            VerParques v = new VerParques('s');
            v.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(EscolherZona.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_SulActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        InicioApp i = new InicioApp();
        i.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void NorteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NorteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Norte.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Centro.requestFocusInWindow();
    }//GEN-LAST:event_NorteKeyPressed

    private void OesteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OesteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Oeste.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) Centro.requestFocusInWindow();
    }//GEN-LAST:event_OesteKeyPressed

    private void CentroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CentroKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Centro.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) Este.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) Oeste.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Norte.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Sul.requestFocusInWindow();
    }//GEN-LAST:event_CentroKeyPressed

    private void EsteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EsteKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Este.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) Centro.requestFocusInWindow();
    }//GEN-LAST:event_EsteKeyPressed

    private void SulKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SulKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Sul.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) Voltar.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Centro.requestFocusInWindow();
    }//GEN-LAST:event_SulKeyPressed

    private void VoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VoltarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP) Sul.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Voltar.doClick();
    }//GEN-LAST:event_VoltarKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Centro;
    private javax.swing.JButton Este;
    private javax.swing.JButton Norte;
    private javax.swing.JButton Oeste;
    private javax.swing.JButton Sul;
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel Zonas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
