/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiuser;

import com.sun.glass.events.KeyEvent;

/**
 *
 * @author Daniel
 */
public class InicioApp extends javax.swing.JFrame {

    /**
     * Creates new form InicioApp
     */
    public InicioApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JButton();
        Registar = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();
        Parques = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Login.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Login.setText("Iniciar sessão");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        Login.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginKeyPressed(evt);
            }
        });

        Registar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Registar.setText("Registar");
        Registar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarActionPerformed(evt);
            }
        });
        Registar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RegistarKeyPressed(evt);
            }
        });

        Fechar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fechar.setText("Fechar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });
        Fechar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FecharKeyPressed(evt);
            }
        });

        Parques.setText("Ver Parques");
        Parques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParquesActionPerformed(evt);
            }
        });
        Parques.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ParquesKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(Registar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Parques))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Fechar, Login, Parques, Registar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Registar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(Parques)
                .addGap(54, 54, 54)
                .addComponent(Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Fechar, Login, Parques});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * método que permite ao utilizador
     * abrir a janela de registo e
     * registar-se na aplicação
     * @see InicioApp
     * @param evt 
     */
    private void RegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarActionPerformed
        Registo r = new Registo();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistarActionPerformed

    /*
    /método que permite ao utilizador
    *abrir a janela de login e 
    *entrar na aplicação com a sua conta
    */
    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginActionPerformed

    /*
    *método que permite ao utilizador
    *terminar por completo a aplicação
    */
    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_FecharActionPerformed

    private void ParquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParquesActionPerformed
        EscolherZona e = new EscolherZona();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ParquesActionPerformed

    private void LoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Login.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) Registar.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Parques.requestFocusInWindow();
    }//GEN-LAST:event_LoginKeyPressed

    private void RegistarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RegistarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Registar.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) Login.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Parques.requestFocusInWindow();
    }//GEN-LAST:event_RegistarKeyPressed

    private void ParquesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ParquesKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) Registar.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) Login.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Fechar.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Parques.doClick();
    }//GEN-LAST:event_ParquesKeyPressed

    private void FecharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FecharKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Fechar.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Parques.requestFocusInWindow();
    }//GEN-LAST:event_FecharKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new InicioApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fechar;
    private javax.swing.JButton Login;
    private javax.swing.JButton Parques;
    private javax.swing.JButton Registar;
    // End of variables declaration//GEN-END:variables
}
