/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiuser;

import com.sun.glass.events.KeyEvent;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import userordinario.Zona;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import userordinario.Ests;
import userordinario.UserOrdinario;
import userpremium.UserPremium;

/**
 *
 * @author Daniel
 * @author Balreira 12 Jan 2019
 */
public class MainPage extends javax.swing.JFrame {
    
    private final ArrayList<String> msgs;
    UserOrdinario u = new UserOrdinario();
    Random r = new Random();
    private Login l;
    UserPremium userP = new UserPremium();
    
    public MainPage(Login l) throws SQLException {
        initComponents();
        msgs = new ArrayList();
        insertRandomMsgs();
        setRandomMsgs();
        this.l = l;
        News1.setEditable(false); News2.setEditable(false);
        News3.setEditable(false);
    }
    
    public void setTitle(){
        jLabelMainPage.setText("Página Inicial");
    }
    
    private void insertRandomMsgs() throws SQLException{
        u.getLugaresLivres(); u.getZonas(); String text;
        float preco = u.getPreco();
        Ests e; Zona z; int limit;
        if(preco < 6){
            String formatpreco = String.format("%.2f", preco);
            msgs.add("PREÇO CONTA PREMIUM A APENAS " + formatpreco + "€!!!!!\nAPROVEITE!!!");
            msgs.add("APROVEITE O QUE TEMOS PARA LHE\nOFERECER SE OBTIVER A CONTA PREMIUM\n"
            + "COMPRE JÁ!!!!!\nPRECO: " + formatpreco + "€");
            msgs.add("COM CONTA PREMIUM\n PODE RESERVAR\n QUALQUER LUGAR!!!\n ADIRA JÁ!!\nPREÇO: " + formatpreco + "€");
        }
        
        if(u.ests.isEmpty()) msgs.add("APROVEITE A CONTA PREMIUM!!");
        else{
            if(u.ests.size() > 3) limit = 3;
            else limit = 1;
            for(int i = 0; i < limit; i++){
                e = u.ests.get(i);
                msgs.add("ESTACIONAMENTO DA\n" + e.getRua().toUpperCase() + " TEM " + e.getTotallugareslivres()
                + " LUGARES LIVRES!!");
            }
        
            if(u.ests.size() > 3) limit = 3;
            else limit = 1;
            text = "LUGARES LIVRES:\n";
            for(int i = 0; i < limit; i++){
                e = u.ests.get(i);
                text += e.getRua().toUpperCase() + " -> " + e.getTotallugareslivres() + "\n";
            }
            msgs.add(text);
        }
        
        int size_zonas = u.zonas.size();
        z = u.zonas.get(r.nextInt(((size_zonas - 1) - 0) + 1) + 0);
        char tipo = z.getTipozona().charAt(0);
        msgs.add("ZONA " + u.getTipozona(tipo) + " COM UM PREÇO P/HORA\nPREMIUM ESTRONDOSO:\n" 
        + String.format("%.2f", z.getCustopremium()) + "€!!!");
        
        if(u.zonas.size() > 3) limit = 3;
        else limit = 1;
        text = "ZONAS PREÇO P/HORA:\n";
        for(int i = 0; i < limit; i++){
            z = u.zonas.get(i);
            text += u.getTipozona(z.getTipozona().charAt(0)) + " -> " + String.format("%.2f", z.getCustoordinario()) + "€\n";
        }
        msgs.add(text);
    }
    
    private void setRandomMsgs(){
        int first = (r.nextInt(((msgs.size() - 1) - 0) + 1) + 0), second, third;
        
        do{
            second = (r.nextInt(((msgs.size() - 1) - 0) + 1) + 0);
        }while(second == first);
        
        do{
            third = (r.nextInt(((msgs.size() - 1) - 0) + 1) + 0);
        }while(third == second || third == first);
        
        News1.setText(msgs.get(first));
        News2.setText(msgs.get(second));
        News3.setText(msgs.get(third));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMainPage = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Perfil = new javax.swing.JButton();
        Parques = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Premium = new javax.swing.JButton();
        Sobre = new javax.swing.JButton();
        Reservar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        News1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        News2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        News3 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelMainPage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMainPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMainPage.setText("BEM-VINDO!");

        Perfil.setText("Ver Perfil");
        Perfil.setToolTipText("Veja seu perfil");
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });
        Perfil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PerfilKeyPressed(evt);
            }
        });

        Parques.setText("Ver Parques");
        Parques.setToolTipText("Tenha acesso aos parques de estacionamento");
        Parques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParquesActionPerformed(evt);
            }
        });
        Parques.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ParquesKeyPressed(evt);
            }
        });

        Logout.setText("Terminar Sessão");
        Logout.setToolTipText("Termina a sessão atual");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        Logout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LogoutKeyPressed(evt);
            }
        });

        Premium.setText("Obter Conta Premium");
        Premium.setToolTipText("Obtenha uma conta Premium");
        Premium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PremiumActionPerformed(evt);
            }
        });
        Premium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PremiumKeyPressed(evt);
            }
        });

        Sobre.setText("Sobre");
        Sobre.setToolTipText("Informa o conceito da aplicação");
        Sobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SobreActionPerformed(evt);
            }
        });
        Sobre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                SobreKeyPressed(evt);
            }
        });

        Reservar.setText("Reservar Lugar");
        Reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarActionPerformed(evt);
            }
        });
        Reservar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ReservarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Premium, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(Reservar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Parques, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Perfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sobre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Perfil, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Parques, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Reservar)
                .addGap(33, 33, 33)
                .addComponent(Premium, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Sobre, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Logout, Parques, Perfil, Premium, Reservar, Sobre});

        News1.setBackground(new java.awt.Color(204, 204, 255));
        News1.setColumns(20);
        News1.setRows(5);
        News1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(News1);

        News2.setBackground(new java.awt.Color(204, 204, 255));
        News2.setColumns(20);
        News2.setRows(5);
        jScrollPane2.setViewportView(News2);

        News3.setBackground(new java.awt.Color(204, 204, 255));
        News3.setColumns(20);
        News3.setRows(5);
        jScrollPane3.setViewportView(News3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMainPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane1))
                        .addGap(0, 60, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelMainPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2, jScrollPane3});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        VerPerfil v = new VerPerfil(l);
        v.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PerfilActionPerformed

    private void PerfilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PerfilKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Perfil.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Parques.requestFocusInWindow();
    }//GEN-LAST:event_PerfilKeyPressed

    private void ParquesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ParquesKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Parques.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Reservar.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Perfil.requestFocusInWindow();
    }//GEN-LAST:event_ParquesKeyPressed

    private void PremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PremiumActionPerformed
        try {
            if(userP.checkPremium(l.getUs())) {
                ContaUpgraded cu = new ContaUpgraded(l);
                cu.setVisible(true);
                this.dispose();
            } else {
                UpgradeConta up = new UpgradeConta(l);
                up.setVisible(true);
                this.dispose();
            }
        } catch (SQLException | NoSuchAlgorithmException | InvalidKeySpecException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_PremiumActionPerformed

    private void PremiumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PremiumKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Premium.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Sobre.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Reservar.requestFocusInWindow();
    }//GEN-LAST:event_PremiumKeyPressed

    private void SobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SobreActionPerformed
        Sobre s = new Sobre(l);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_SobreActionPerformed

    private void SobreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SobreKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Sobre.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Logout.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Premium.requestFocusInWindow();
    }//GEN-LAST:event_SobreKeyPressed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void LogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LogoutKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Logout.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Sobre.requestFocusInWindow();
    }//GEN-LAST:event_LogoutKeyPressed

    private void ReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarActionPerformed
        EscolherZonaReserva re = new EscolherZonaReserva(l);
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReservarActionPerformed

    private void ReservarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReservarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Reservar.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Premium.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Parques.requestFocusInWindow();
    }//GEN-LAST:event_ReservarKeyPressed

    private void ParquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParquesActionPerformed
        EscolherZonaUser zona = new EscolherZonaUser(l);
        zona.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ParquesActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JTextArea News1;
    private javax.swing.JTextArea News2;
    private javax.swing.JTextArea News3;
    private javax.swing.JButton Parques;
    private javax.swing.JButton Perfil;
    private javax.swing.JButton Premium;
    private javax.swing.JButton Reservar;
    private javax.swing.JButton Sobre;
    private javax.swing.JLabel jLabelMainPage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
