/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiuser;

import checkdata.CheckData;
import com.sun.glass.events.KeyEvent;
import connection.Conexao;
import generatedata.UserSaldo;
import java.awt.Color;
import java.beans.PropertyChangeEvent;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import userordinario.UserOrdinario;


/**
 *
 * @author Daniel
 * @author Balreira 08 Jan 2019
 */
public class Registo extends javax.swing.JFrame {
    
    Conexao connect = new Conexao();
    UserOrdinario u = new UserOrdinario();
    ArrayList <JTextField> lista;
    CheckData c = new CheckData();
    private Date date = null;
    UserSaldo us = new UserSaldo();
    
    public Registo() {
        initComponents();
        getDataNasc();
        lista = new ArrayList();
    }
    
    private void addFields(){
        JTextField x = FieldPass;
        lista.add(FieldNome); lista.add(FieldMorada); lista.add(FieldCodPostal); 
        lista.add(FieldBi); lista.add(FieldNif); lista.add(FieldEmail); 
        lista.add(FieldIban); lista.add(FieldMatricula); lista.add(FieldMarca); 
        lista.add(FieldModelo); lista.add(FieldTele); lista.add(x);
    }
    
    public void setColor(JTextField x){
        x.setBackground(Color.white);
        x.setForeground(Color.black);
    }
    
    public void checkEmptyField(JTextField x){
        if(x.getText().length() == 0) x.setBackground(Color.red);
    }
    
    public void replaceText(java.awt.event.FocusEvent evt, String text){
        JTextField t = (JTextField)evt.getSource();
        if(t.getText().length() == 0){
            t.setText(text);
            t.setForeground(Color.GRAY);
        }
        t.selectAll();
    }
    
    protected void checkFormatter(JTextField x, int length){
        if(x.getText().length() < length){
            x.setText("");
            x.setBackground(Color.red);
        }
    }
    
    public void setFormatterM(java.awt.event.KeyEvent evt, JTextField x){
        boolean key = evt.getKeyCode() != KeyEvent.VK_BACKSPACE;
        int length = x.getText().length();
        if(length == 2 && key) x.setText(x.getText().substring(0, 2) + "-");
        if(length == 5 && key) x.setText(x.getText().substring(0, 5) + "-");
    }
    
    protected void setFormatterCp(java.awt.event.KeyEvent evt, JTextField x){
        int length = x.getText().length();
        if(length == 4 && evt.getKeyCode() != KeyEvent.VK_BACKSPACE)
            x.setText(x.getText().substring(0, 4) + "-");
    }
    
    protected void requestFocus(JTextField actual, JTextField next, int length){
        if(actual.getText().length() == length) next.requestFocus();
    }
    
    protected void deleteText(java.awt.event.KeyEvent evt, JTextField x){
        String text = x.getText();
        if(evt.getKeyCode() == KeyEvent.VK_BACKSPACE) x.setText(text.substring(0, text.length()));
    }
    
    private void getDataNasc(){
        FieldDataNasc.addPropertyChangeListener("date", (PropertyChangeEvent evt) -> {
            date = FieldDataNasc.getDate();
        });
    }
    
    private float randomSaldo(){
        return us.randomSaldo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Registo = new javax.swing.JLabel();
        InfoBasica = new javax.swing.JPanel();
        Nome = new javax.swing.JLabel();
        DataNasc = new javax.swing.JLabel();
        Morada = new javax.swing.JLabel();
        FieldMorada = new javax.swing.JTextField();
        CodPostal = new javax.swing.JLabel();
        CC = new javax.swing.JLabel();
        Nif = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        FieldEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MetodoPag = new javax.swing.JLabel();
        BoxMetodoPag = new javax.swing.JComboBox<>();
        FieldNome = new javax.swing.JTextField();
        FieldDataNasc = new com.toedter.calendar.JDateChooser();
        FieldCodPostal = new javax.swing.JTextField();
        FieldNif = new javax.swing.JTextField();
        FieldIban = new javax.swing.JTextField();
        FieldBi = new javax.swing.JTextField();
        Conta = new javax.swing.JPanel();
        Telemovel = new javax.swing.JLabel();
        Pass = new javax.swing.JLabel();
        FieldPass = new javax.swing.JPasswordField();
        FieldTele = new javax.swing.JTextField();
        OK = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        ContaPremium = new javax.swing.JRadioButton();
        MaiorIdade = new javax.swing.JRadioButton();
        Veiculo = new javax.swing.JPanel();
        Matricula = new javax.swing.JLabel();
        Marca = new javax.swing.JLabel();
        FieldMarca = new javax.swing.JTextField();
        Modelo = new javax.swing.JLabel();
        FieldModelo = new javax.swing.JTextField();
        FieldMatricula = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Registo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Registo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Registo.setText("Registo");

        InfoBasica.setBorder(javax.swing.BorderFactory.createTitledBorder("Informação Básica"));

        Nome.setText("Nome:");

        DataNasc.setText("Data de Nascimento:");

        Morada.setText("Morada:");

        FieldMorada.setForeground(java.awt.Color.gray);
        FieldMorada.setText("Rua...");
        FieldMorada.setToolTipText("Insira a sua morada");
        FieldMorada.setName("Morada"); // NOI18N
        FieldMorada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldMoradaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldMoradaFocusLost(evt);
            }
        });
        FieldMorada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldMoradaKeyPressed(evt);
            }
        });

        CodPostal.setText("Código-postal:");

        CC.setText("Nº Cartão de Cidadão:");

        Nif.setText("Nº de Contribuinte:");

        Email.setText("E-mail:");

        FieldEmail.setForeground(java.awt.Color.gray);
        FieldEmail.setText("exemplo@exemplo.pt");
        FieldEmail.setToolTipText("Insira o seu endereço eletrónico");
        FieldEmail.setName("E-mail"); // NOI18N
        FieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldEmailFocusLost(evt);
            }
        });
        FieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldEmailKeyPressed(evt);
            }
        });

        jLabel2.setText("IBAN:");

        MetodoPag.setText("Método Pagamento:");

        BoxMetodoPag.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MultiBanco", "PayPal" }));
        BoxMetodoPag.setToolTipText("Forma como deseja pagar");
        BoxMetodoPag.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BoxMetodoPagFocusGained(evt);
            }
        });

        FieldNome.setForeground(java.awt.Color.gray);
        FieldNome.setText("Exemplo");
        FieldNome.setToolTipText("Insira o seu nome");
        FieldNome.setName("Nome"); // NOI18N
        FieldNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldNomeFocusLost(evt);
            }
        });
        FieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldNomeKeyPressed(evt);
            }
        });

        FieldDataNasc.setToolTipText("dd-MM-yyyy");
        FieldDataNasc.setDateFormatString("dd-MM-yyyy");
        FieldDataNasc.setName("Data de Nascimento"); // NOI18N

        FieldCodPostal.setForeground(java.awt.Color.gray);
        FieldCodPostal.setText("1000-100");
        FieldCodPostal.setToolTipText("Insira o seu código-postal (Ex: 3000-100)");
        FieldCodPostal.setName("Código-postal"); // NOI18N
        FieldCodPostal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldCodPostalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldCodPostalFocusLost(evt);
            }
        });
        FieldCodPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldCodPostalKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldCodPostalKeyReleased(evt);
            }
        });

        FieldNif.setForeground(java.awt.Color.gray);
        FieldNif.setText("263489361");
        FieldNif.setToolTipText("Insira o número de identificação fiscal");
        FieldNif.setName("Nº de Contribuinte"); // NOI18N
        FieldNif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldNifFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldNifFocusLost(evt);
            }
        });
        FieldNif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldNifKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldNifKeyReleased(evt);
            }
        });

        FieldIban.setForeground(java.awt.Color.gray);
        FieldIban.setText("1234567890123456");
        FieldIban.setToolTipText("Insira o seu IBAN");
        FieldIban.setName("IBAN"); // NOI18N
        FieldIban.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldIbanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldIbanFocusLost(evt);
            }
        });
        FieldIban.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldIbanKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldIbanKeyReleased(evt);
            }
        });

        FieldBi.setForeground(java.awt.Color.gray);
        FieldBi.setText("12345678");
        FieldBi.setToolTipText("Insira o número do CC");
        FieldBi.setName("Nº Cartão de Cidadão"); // NOI18N
        FieldBi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldBiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldBiFocusLost(evt);
            }
        });
        FieldBi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldBiKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldBiKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout InfoBasicaLayout = new javax.swing.GroupLayout(InfoBasica);
        InfoBasica.setLayout(InfoBasicaLayout);
        InfoBasicaLayout.setHorizontalGroup(
            InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(InfoBasicaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Morada)
                    .addComponent(CodPostal)
                    .addComponent(Nif)
                    .addComponent(jLabel2)
                    .addComponent(Nome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoBasicaLayout.createSequentialGroup()
                        .addComponent(FieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DataNasc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoBasicaLayout.createSequentialGroup()
                        .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FieldCodPostal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(FieldIban, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                                .addComponent(FieldNif)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MetodoPag, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(FieldEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(FieldBi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BoxMetodoPag, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(FieldMorada))
                .addContainerGap())
        );
        InfoBasicaLayout.setVerticalGroup(
            InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoBasicaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(FieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Nome)
                        .addComponent(DataNasc))
                    .addComponent(FieldDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Morada)
                    .addComponent(FieldMorada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CodPostal)
                    .addComponent(CC)
                    .addComponent(FieldCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldBi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nif)
                    .addComponent(Email)
                    .addComponent(FieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoBasicaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(InfoBasicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(BoxMetodoPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FieldIban, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoBasicaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MetodoPag)))
                .addContainerGap())
        );

        Conta.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta"));

        Telemovel.setText("Nº de Telemóvel:");

        Pass.setText("Palavra-passe:");

        FieldPass.setForeground(java.awt.Color.gray);
        FieldPass.setText("123455667");
        FieldPass.setToolTipText("Insira uma palavra-passe para autenticação");
        FieldPass.setName("Palavra-passe"); // NOI18N
        FieldPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldPassFocusGained(evt);
            }
        });
        FieldPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldPassKeyPressed(evt);
            }
        });

        FieldTele.setForeground(java.awt.Color.gray);
        FieldTele.setText("912302573");
        FieldTele.setToolTipText("Insira o seu contacto");
        FieldTele.setName("Nº de telemóvel"); // NOI18N
        FieldTele.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldTeleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldTeleFocusLost(evt);
            }
        });
        FieldTele.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldTeleKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldTeleKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout ContaLayout = new javax.swing.GroupLayout(Conta);
        Conta.setLayout(ContaLayout);
        ContaLayout.setHorizontalGroup(
            ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Telemovel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FieldTele, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 330, Short.MAX_VALUE)
                .addComponent(Pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ContaLayout.setVerticalGroup(
            ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telemovel)
                    .addComponent(Pass)
                    .addComponent(FieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        OK.setText("OK");
        OK.setToolTipText("Para continuar");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        OK.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OKKeyPressed(evt);
            }
        });

        Cancel.setText("Cancelar");
        Cancel.setToolTipText("Rejeitar registo");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        Cancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CancelKeyPressed(evt);
            }
        });

        ContaPremium.setText("Aderir à Conta Premium");
        ContaPremium.setToolTipText("Facultativo");
        ContaPremium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ContaPremiumKeyPressed(evt);
            }
        });

        MaiorIdade.setText("Tenho, pelo menos, 18 anos de idade");
        MaiorIdade.setToolTipText("Campo Obrigatório");
        MaiorIdade.setName(""); // NOI18N
        MaiorIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MaiorIdadeKeyPressed(evt);
            }
        });

        Veiculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Veículo"));

        Matricula.setText("Matrícula:");

        Marca.setText("Marca:");

        FieldMarca.setForeground(java.awt.Color.gray);
        FieldMarca.setText("X");
        FieldMarca.setToolTipText("Marca do veículo");
        FieldMarca.setName("Name"); // NOI18N
        FieldMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldMarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldMarcaFocusLost(evt);
            }
        });
        FieldMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldMarcaKeyPressed(evt);
            }
        });

        Modelo.setText("Modelo:");

        FieldModelo.setForeground(java.awt.Color.gray);
        FieldModelo.setText("Y");
        FieldModelo.setToolTipText("Modelo do veículo");
        FieldModelo.setName("Modelo"); // NOI18N
        FieldModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldModeloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldModeloFocusLost(evt);
            }
        });
        FieldModelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldModeloKeyPressed(evt);
            }
        });

        FieldMatricula.setForeground(java.awt.Color.gray);
        FieldMatricula.setText("AA-00-AA");
        FieldMatricula.setToolTipText("Insira a matrícula do seu veículo");
        FieldMatricula.setName("Matrícula"); // NOI18N
        FieldMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FieldMatriculaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FieldMatriculaFocusLost(evt);
            }
        });
        FieldMatricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FieldMatriculaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FieldMatriculaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout VeiculoLayout = new javax.swing.GroupLayout(Veiculo);
        Veiculo.setLayout(VeiculoLayout);
        VeiculoLayout.setHorizontalGroup(
            VeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VeiculoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(VeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Matricula)
                    .addComponent(Modelo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FieldModelo)
                    .addComponent(FieldMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Marca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        VeiculoLayout.setVerticalGroup(
            VeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VeiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(VeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marca)
                    .addComponent(FieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Matricula)
                    .addComponent(FieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(VeiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modelo)
                    .addComponent(FieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MaiorIdade)
                        .addGap(41, 41, 41)
                        .addComponent(ContaPremium))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(OK)
                                .addGap(18, 18, 18)
                                .addComponent(Cancel))
                            .addComponent(Registo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(InfoBasica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Conta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Veiculo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Cancel, OK});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Registo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InfoBasica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Conta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContaPremium)
                    .addComponent(MaiorIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OK)
                    .addComponent(Cancel))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FieldNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldNomeFocusGained
        replaceText(evt, "Exemplo");
    }//GEN-LAST:event_FieldNomeFocusGained

    private void FieldNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldNomeFocusLost
        checkEmptyField(FieldNome);
    }//GEN-LAST:event_FieldNomeFocusLost

    private void FieldNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNomeKeyPressed
        setColor(FieldNome);
    }//GEN-LAST:event_FieldNomeKeyPressed

    private void FieldMoradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldMoradaFocusGained
        replaceText(evt, "Rua...");
    }//GEN-LAST:event_FieldMoradaFocusGained

    private void FieldMoradaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldMoradaFocusLost
        checkEmptyField(FieldMorada);
    }//GEN-LAST:event_FieldMoradaFocusLost

    private void FieldMoradaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldMoradaKeyPressed
        setColor(FieldMorada);
    }//GEN-LAST:event_FieldMoradaKeyPressed

    private void FieldCodPostalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldCodPostalFocusGained
        replaceText(evt, "1000-100");
    }//GEN-LAST:event_FieldCodPostalFocusGained

    private void FieldCodPostalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldCodPostalFocusLost
        JTextField cp = FieldCodPostal;
        checkFormatter(cp, 8);
        if(!c.check_codPostal(cp.getText())) cp.setForeground(Color.red);
    }//GEN-LAST:event_FieldCodPostalFocusLost

    private void FieldCodPostalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldCodPostalKeyPressed
        JTextField cp = FieldCodPostal;
        setColor(cp);
        setFormatterCp(evt, cp);
        deleteText(evt, cp);
    }//GEN-LAST:event_FieldCodPostalKeyPressed

    private void FieldCodPostalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldCodPostalKeyReleased
        requestFocus(FieldCodPostal, FieldBi, 8);
    }//GEN-LAST:event_FieldCodPostalKeyReleased

    private void FieldBiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldBiFocusGained
        replaceText(evt, "12345678");
    }//GEN-LAST:event_FieldBiFocusGained

    private void FieldBiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldBiFocusLost
        JTextField bi = FieldBi;
        checkFormatter(bi, 8);
        if(!c.check_BI(bi.getText())) bi.setForeground(Color.red);
        try {
            if(u.check_bi(bi.getText())) bi.setForeground(Color.red);
        } catch (SQLException | NoSuchAlgorithmException | InvalidKeySpecException ex) {
            Logger.getLogger(Registo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FieldBiFocusLost

    private void FieldBiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldBiKeyPressed
        setColor(FieldBi);
    }//GEN-LAST:event_FieldBiKeyPressed

    private void FieldBiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldBiKeyReleased
        requestFocus(FieldBi, FieldNif, 8);
    }//GEN-LAST:event_FieldBiKeyReleased

    private void FieldNifFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldNifFocusGained
        replaceText(evt, "263489361");
    }//GEN-LAST:event_FieldNifFocusGained

    private void FieldNifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldNifFocusLost
        JTextField nif = FieldNif;
        checkFormatter(nif, 9);
        if(!c.check_NIF(nif.getText())) nif.setForeground(Color.red);
        try {
            if(u.check_nif(nif.getText())) nif.setForeground(Color.red);
        } catch (SQLException | NoSuchAlgorithmException | InvalidKeySpecException ex) {
            Logger.getLogger(Registo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FieldNifFocusLost

    private void FieldNifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNifKeyPressed
        setColor(FieldNif);
    }//GEN-LAST:event_FieldNifKeyPressed

    private void FieldNifKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldNifKeyReleased
        requestFocus(FieldNif, FieldEmail, 9);
    }//GEN-LAST:event_FieldNifKeyReleased

    private void FieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldEmailFocusGained
        replaceText(evt, "exemplo@exemplo.pt");
    }//GEN-LAST:event_FieldEmailFocusGained

    private void FieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldEmailFocusLost
        JTextField e = FieldEmail;
        checkEmptyField(e);
        if(!c.check_email(e.getText())) e.setForeground(Color.red);
    }//GEN-LAST:event_FieldEmailFocusLost

    private void FieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldEmailKeyPressed
        setColor(FieldEmail);
    }//GEN-LAST:event_FieldEmailKeyPressed

    private void FieldIbanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldIbanFocusGained
        replaceText(evt, "1234567890123456");
    }//GEN-LAST:event_FieldIbanFocusGained

    private void FieldIbanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldIbanFocusLost
        JTextField iban = FieldIban;
        checkFormatter(iban, 16);
        if(!c.check_numMB(iban.getText())) iban.setForeground(Color.red);
    }//GEN-LAST:event_FieldIbanFocusLost

    private void FieldIbanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldIbanKeyPressed
        setColor(FieldIban);
    }//GEN-LAST:event_FieldIbanKeyPressed

    private void FieldIbanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldIbanKeyReleased
        if(FieldIban.getText().length() == 16){
            BoxMetodoPag.requestFocusInWindow();
            BoxMetodoPag.showPopup();
        }
    }//GEN-LAST:event_FieldIbanKeyReleased

    private void FieldMatriculaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldMatriculaFocusGained
        replaceText(evt, "AA-00-AA");
    }//GEN-LAST:event_FieldMatriculaFocusGained

    private void FieldMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldMatriculaFocusLost
        JTextField m = FieldMatricula;
        checkFormatter(m, 8);
        if(!c.check_matricula(m.getText())) m.setForeground(Color.red);
        try {
            if(u.check_matricula(m.getText())) m.setForeground(Color.red);
        } catch (SQLException | NoSuchAlgorithmException | InvalidKeySpecException ex) {
            Logger.getLogger(Registo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FieldMatriculaFocusLost

    private void FieldMatriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldMatriculaKeyPressed
        JTextField cp = FieldMatricula;
        setColor(cp);
        setFormatterM(evt, cp);
        deleteText(evt, cp);
    }//GEN-LAST:event_FieldMatriculaKeyPressed

    private void FieldMatriculaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldMatriculaKeyReleased
        requestFocus(FieldMatricula, FieldMarca, 8);
    }//GEN-LAST:event_FieldMatriculaKeyReleased

    private void FieldMarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldMarcaFocusGained
        replaceText(evt, "X");
    }//GEN-LAST:event_FieldMarcaFocusGained

    private void FieldMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldMarcaFocusLost
        checkEmptyField(FieldMarca);
    }//GEN-LAST:event_FieldMarcaFocusLost

    private void FieldMarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldMarcaKeyPressed
        setColor(FieldMarca);
    }//GEN-LAST:event_FieldMarcaKeyPressed

    private void FieldModeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldModeloFocusGained
        replaceText(evt, "Y");
    }//GEN-LAST:event_FieldModeloFocusGained

    private void FieldModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldModeloFocusLost
        checkEmptyField(FieldModelo);
    }//GEN-LAST:event_FieldModeloFocusLost

    private void FieldModeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldModeloKeyPressed
        setColor(FieldModelo);
    }//GEN-LAST:event_FieldModeloKeyPressed

    private void FieldTeleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldTeleFocusGained
        replaceText(evt, "912302573");
    }//GEN-LAST:event_FieldTeleFocusGained

    private void FieldTeleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldTeleFocusLost
        JTextField t = FieldTele;
        checkFormatter(t, 9);
        if(!c.check_telemovel(t.getText())) t.setForeground(Color.red);
    }//GEN-LAST:event_FieldTeleFocusLost

    private void FieldTeleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldTeleKeyPressed
        setColor(FieldTele);
    }//GEN-LAST:event_FieldTeleKeyPressed

    private void FieldTeleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldTeleKeyReleased
        requestFocus(FieldTele, FieldPass, 9);
    }//GEN-LAST:event_FieldTeleKeyReleased

    private void FieldPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FieldPassFocusGained
        replaceText(evt, "12345678");
    }//GEN-LAST:event_FieldPassFocusGained

    private void FieldPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FieldPassKeyPressed
        JTextField p = FieldPass; int score = c.password_strength(p.getText());
        setColor(p);
        if(score == 0) p.setForeground(Color.red);
        if(score >= 2 && score <= 6) p.setForeground(Color.yellow);
        if(score >= 8 && score <= 10) p.setForeground(Color.green);
    }//GEN-LAST:event_FieldPassKeyPressed

    private void MaiorIdadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MaiorIdadeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) MaiorIdade.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) ContaPremium.requestFocusInWindow();
    }//GEN-LAST:event_MaiorIdadeKeyPressed

    private void ContaPremiumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ContaPremiumKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) ContaPremium.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) MaiorIdade.requestFocusInWindow();
    }//GEN-LAST:event_ContaPremiumKeyPressed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        addFields(); boolean empty = false; ArrayList<JTextField> invalid = new ArrayList();
        boolean maioridade = MaiorIdade.isSelected(), premium = ContaPremium.isSelected();
        JTextField pass = FieldPass;
        String msg = ""; float s = randomSaldo();
        for(JTextField j : lista){
            if(j.getBackground() == Color.red || j.getForeground() == Color.gray || j.getText().trim().isEmpty()){
                empty = true;
                break;
            }
        }
        if(empty) msg = "Existem campos vazios!";
        else{
            for(JTextField j : lista) if(j.getForeground() == Color.red) invalid.add(j);
            if(!invalid.isEmpty()){
                msg += "Campos inválidos:\n";
                for(JTextField j : invalid) msg += "\"" + j.getName() + "\"" + "\n";
            }
        
            try {
                JTextField x = ((JTextField)FieldDataNasc.getDateEditor().getUiComponent());
                if(x.getForeground() == Color.red || date == null) msg += "\"" + FieldDataNasc.getName() + "\"\n";
                else
                    if(u.check_data(date) < 18) msg += "A idade do utilizador deve ser igual ou superior a 18 anos";
            } catch (ParseException ex) {
                Logger.getLogger(Registo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            Color data = FieldPass.getForeground();
            if(data == Color.red) msg += "Palavra-passe deve conter, pelo menos, 8 caracteres";
            if(data == Color.yellow) msg += "Palavra-passe fraca. Deve conter, pelo menos, uma letra maiúscula e um caractere especial";
        }
        
        if(!msg.equals("")){
            JOptionPane.showMessageDialog(null, msg, "Campos inválidos", JOptionPane.ERROR_MESSAGE);

        }
        else{
            if(!maioridade)
                JOptionPane.showMessageDialog(null, "O campo \"Tenho, pelo menos, 18 anos de idade\" "
                + "é obrigatório!", "Campo Obrigatório", JOptionPane.WARNING_MESSAGE);
            else{
                int termos = JOptionPane.showConfirmDialog(null,
                "Tomo conhecimento que esta entidade proceda à recolha e tratamento dos meus dados pessoais.", 
                "Legislação", JOptionPane.YES_NO_OPTION);
                if(termos == JOptionPane.YES_OPTION){
                    int option = JOptionPane.showConfirmDialog(null, "Tem a certeza de que deseja continuar?", 
                    "ATENÇÃO", JOptionPane.YES_NO_OPTION);
                    if(option == JOptionPane.YES_OPTION){
                        String m = BoxMetodoPag.getSelectedItem().toString();
                        try {
                            u.insertUser(FieldBi.getText(), FieldNif.getText(), date, FieldEmail.getText(),
                            FieldNome.getText(), FieldMorada.getText(), FieldCodPostal.getText(),
                            FieldTele.getText(), pass.getText(),(short) 0, FieldIban.getText(),
                            s, u.getMetodoPag(m), u.uppercaseMatricula(FieldMatricula.getText()), FieldMarca.getText(), 
                            FieldModelo.getText());
                        } catch (SQLException | NoSuchAlgorithmException | InvalidKeySpecException | UnsupportedEncodingException | InvalidKeyException | NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
                            Logger.getLogger(Registo.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if(premium){
                            try {
                                if(s < u.getPreco())
                                    JOptionPane.showMessageDialog(null, 
                                    "Lamentamos mas não tem saldo suficiente para obter a conta Premium.",
                                    "Saldo insuficiente", JOptionPane.INFORMATION_MESSAGE);
                                else{
                                    try {
                                        u.setPremiumConta(FieldBi.getText());
                                    } catch (NoSuchAlgorithmException | InvalidKeySpecException ex) {
                                        JOptionPane.showMessageDialog(null, ex.getMessage(), "ERRO", JOptionPane.ERROR_MESSAGE);
                                    }
                                    JOptionPane.showMessageDialog(null, "A conta Premium foi obtida com sucesso!", "CONTA PREMIUM", JOptionPane.INFORMATION_MESSAGE);
                                }
                                    } catch (SQLException ex) {
                                Logger.getLogger(Registo.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                        JOptionPane.showMessageDialog(null, "Os dados foram submetidos com sucesso! Obrigado pela sua preferência!", 
                        "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                        InicioApp i = new InicioApp();
                        i.setVisible(true);
                        this.dispose();
                    }                
                }
            }
        }
    }//GEN-LAST:event_OKActionPerformed

    private void OKKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OKKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) OK.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) Cancel.requestFocusInWindow();
    }//GEN-LAST:event_OKKeyPressed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        addFields(); int count = 0;
        for(JTextField j : lista)
            if(j.getForeground() == Color.gray || j.getText().trim().isEmpty()) count++;
        
        if(count == lista.size()){
            JTextField d = ((JTextField)FieldDataNasc.getDateEditor().getUiComponent()), p = FieldPass;
            if(d.getText().trim().isEmpty()) count++;
            if(p.getText().trim().isEmpty() || p.getForeground() == Color.gray) count++;
        }
        
        if(count < lista.size() + 2){
            int option = JOptionPane.showConfirmDialog(null, "Ao cancelar irá perder todos os dados inseridos. Tem a certeza"
            + " que deseja continuar?", "ATENÇÃO", JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                cancelRegister();
            }
        }else
            cancelRegister();
    }//GEN-LAST:event_CancelActionPerformed

    private void cancelRegister(){
        InicioApp i = new InicioApp();
        i.setVisible(true);
        this.dispose();
    }
        
    private void CancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CancelKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Cancel.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) OK.requestFocusInWindow();
    }//GEN-LAST:event_CancelKeyPressed

    private void BoxMetodoPagFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BoxMetodoPagFocusGained
        BoxMetodoPag.showPopup();
    }//GEN-LAST:event_BoxMetodoPagFocusGained

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxMetodoPag;
    private javax.swing.JLabel CC;
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel CodPostal;
    private javax.swing.JPanel Conta;
    private javax.swing.JRadioButton ContaPremium;
    private javax.swing.JLabel DataNasc;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField FieldBi;
    private javax.swing.JTextField FieldCodPostal;
    private com.toedter.calendar.JDateChooser FieldDataNasc;
    private javax.swing.JTextField FieldEmail;
    private javax.swing.JTextField FieldIban;
    private javax.swing.JTextField FieldMarca;
    private javax.swing.JTextField FieldMatricula;
    private javax.swing.JTextField FieldModelo;
    private javax.swing.JTextField FieldMorada;
    private javax.swing.JTextField FieldNif;
    private javax.swing.JTextField FieldNome;
    private javax.swing.JPasswordField FieldPass;
    private javax.swing.JTextField FieldTele;
    private javax.swing.JPanel InfoBasica;
    private javax.swing.JRadioButton MaiorIdade;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Matricula;
    private javax.swing.JLabel MetodoPag;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel Morada;
    private javax.swing.JLabel Nif;
    private javax.swing.JLabel Nome;
    private javax.swing.JButton OK;
    private javax.swing.JLabel Pass;
    private javax.swing.JLabel Registo;
    private javax.swing.JLabel Telemovel;
    private javax.swing.JPanel Veiculo;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
