/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiuser;

import connection.Conexao;
import convidado.Convidado;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import userordinario.Ests;
import userpremium.Estacionamento;
import userpremium.UserPremium;

/**
 *
 * @author danie
 */
public class ReservarLugar extends javax.swing.JFrame {

    Conexao connect = new Conexao();
    Connection conn = null;
    Statement stmt = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    Convidado guest = new Convidado();
    Ests est = new Ests();
    UserPremium user = new UserPremium();
    private Login l;
    Estacionamento e = new Estacionamento();
    
    /**
     * 
     * @param tipozona
     * @param l
     * @throws java.sql.SQLException
     * 
     */
    public ReservarLugar(char tipozona, Login l) throws SQLException {
        initComponents();
        setPrecoZona(tipozona);
        generateTable(tipozona);
        this.l = l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Parques = new javax.swing.JTable();
        Preco = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        Reservar = new javax.swing.JButton();
        Rua = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Parques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rua", "Código-Postal", "Nº total de lugares", "Nº de lugares livres", "Nº de lugares ocupados"
            }
        ));
        jScrollPane1.setViewportView(Parques);
        if (Parques.getColumnModel().getColumnCount() > 0) {
            Parques.getColumnModel().getColumn(0).setPreferredWidth(100);
            Parques.getColumnModel().getColumn(1).setPreferredWidth(40);
            Parques.getColumnModel().getColumn(2).setPreferredWidth(50);
            Parques.getColumnModel().getColumn(3).setPreferredWidth(55);
        }

        Preco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });

        Reservar.setText("Reservar");
        Reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Rua, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Voltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Reservar)
                    .addComponent(Rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        EscolherZonaReserva re = new EscolherZonaReserva(l);
        re.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void ReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarActionPerformed

    }//GEN-LAST:event_ReservarActionPerformed

    private void setPrecoZona(char tipozona) throws SQLException{
        Preco.setText("Preço: " + user.getPrecoZonaPremium(tipozona) + "€ p/hora");
    }
    
    public void generateTable(char tipozona) throws SQLException {
        est.getEstsZona(tipozona);
        DefaultTableModel model = (DefaultTableModel) Parques.getModel();
        model.setRowCount(0);
        for(Ests e : est.parques){
            model.addRow(new Object[]{
                e.getRua(),
                e.getCodpostal(),
                e.getTotallugares(),
                e.getTotallugareslivres(),
                e.getTotallugaresocupados(),
            });
        }
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        Parques.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        Parques.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        Parques.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        Parques.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Parques;
    private javax.swing.JLabel Preco;
    private javax.swing.JButton Reservar;
    private javax.swing.JComboBox<String> Rua;
    private javax.swing.JButton Voltar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
