/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiuser;

import connection.Conexao;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import userordinario.Ests;
import userpremium.UserPremium;

/**
 *
 * @author danie
 */
public class VerParquesPremium extends javax.swing.JFrame {

    Conexao connect = new Conexao();
    Connection conn = null;
    Statement stmt = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;
    UserPremium up = new UserPremium();
    Ests est = new Ests();
    private Login l;
    
    /**
     * Creates new form VerParquesPremium
     * @param tipozona
     * @param l
     * @throws java.sql.SQLException
     */
    public VerParquesPremium(char tipozona, Login l) throws SQLException {
        initComponents();
        setPrecoZona(tipozona);
        generateTable(tipozona);
        this.l = l;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Parques = new javax.swing.JTable();
        Preco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        Voltar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VoltarKeyPressed(evt);
            }
        });

        Parques.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Rua", "Código-Postal", "Nº total de lugares", "Nº de lugares livres", "Nº de lugares ocupados"
            }
        ));
        jScrollPane1.setViewportView(Parques);

        Preco.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Voltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Voltar)
                    .addComponent(Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        EscolherZonaUser zonaU = new EscolherZonaUser(l);
        zonaU.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void VoltarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VoltarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Voltar.doClick();
    }//GEN-LAST:event_VoltarKeyPressed

    private void setPrecoZona(char tipozona) throws SQLException{
        Preco.setText("Preço: " + up.getPrecoZonaPremium(tipozona) + "€ p/hora");
    }
    
    private void generateTable(char tipozona) throws SQLException{
        est.getEstsZona(tipozona);
        DefaultTableModel model = (DefaultTableModel) Parques.getModel();
        model.setRowCount(0);
        for(Ests e : est.parques){
            model.addRow(new Object[]{
                e.getRua(),
                e.getCodpostal(),
                e.getTotallugares(),
                e.getTotallugareslivres(),
                e.getTotallugaresocupados()
            });
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        Parques.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        Parques.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        Parques.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        Parques.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Parques;
    private javax.swing.JLabel Preco;
    private javax.swing.JButton Voltar;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
