/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guiuser;

import com.sun.glass.events.KeyEvent;
import connection.Conexao;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;
import userordinario.UserOrdinario;
import userpremium.UserPremium;

/**
 *
 * @author Daniel
 * @author Balreira 12 Jan 2019
 */
public class VerPerfil extends javax.swing.JFrame {

    Conexao connect = new Conexao();
    UserPremium u = new UserPremium();
    UserOrdinario uo = new UserOrdinario();
    private Login l;
    
    public VerPerfil(Login l){
        try {
            initComponents();
            this.l = l;
            if(uo.checkAvaliacao(l.getUs())) Avaliar.setEnabled(false);
        } catch (SQLException | NoSuchAlgorithmException | InvalidKeySpecException ex) {
            Logger.getLogger(VerPerfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelVerPefil = new javax.swing.JLabel();
        VerDados = new javax.swing.JButton();
        Avaliar = new javax.swing.JButton();
        Matriculas = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        Return = new javax.swing.JButton();
        Premium = new javax.swing.JButton();
        Pagamentos = new javax.swing.JButton();
        Remove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelVerPefil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelVerPefil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVerPefil.setText("Ver Perfil");

        VerDados.setText("Ver dados");
        VerDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerDadosActionPerformed(evt);
            }
        });
        VerDados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VerDadosKeyPressed(evt);
            }
        });

        Avaliar.setText("Classificar Aplicação");
        Avaliar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvaliarActionPerformed(evt);
            }
        });
        Avaliar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AvaliarKeyPressed(evt);
            }
        });

        Matriculas.setText("Gerir matrículas");
        Matriculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculasActionPerformed(evt);
            }
        });
        Matriculas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                MatriculasKeyPressed(evt);
            }
        });

        Logout.setText("Terminar sessão");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        Logout.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LogoutKeyPressed(evt);
            }
        });

        Return.setText("Voltar");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        Return.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ReturnKeyPressed(evt);
            }
        });

        Premium.setText("Obter Conta Premium");
        Premium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PremiumActionPerformed(evt);
            }
        });
        Premium.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PremiumKeyPressed(evt);
            }
        });

        Pagamentos.setText("Histórico de Pagamentos");
        Pagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagamentosActionPerformed(evt);
            }
        });
        Pagamentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PagamentosKeyPressed(evt);
            }
        });

        Remove.setText("Remover conta");
        Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveActionPerformed(evt);
            }
        });
        Remove.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                RemoveKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelVerPefil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 84, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Avaliar)
                            .addComponent(Matriculas)
                            .addComponent(Pagamentos)
                            .addComponent(VerDados)
                            .addComponent(Premium)
                            .addComponent(Remove))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Return)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Logout)
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Avaliar, Matriculas, Pagamentos, Premium, Remove, VerDados});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Logout, Return});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelVerPefil)
                .addGap(45, 45, 45)
                .addComponent(VerDados)
                .addGap(45, 45, 45)
                .addComponent(Premium)
                .addGap(46, 46, 46)
                .addComponent(Matriculas)
                .addGap(47, 47, 47)
                .addComponent(Pagamentos)
                .addGap(42, 42, 42)
                .addComponent(Avaliar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(Remove)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Return))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Avaliar, Matriculas, Pagamentos, Premium, Remove, VerDados});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Logout, Return});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VerDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerDadosActionPerformed
        try {
            VerDados v = new VerDados(l);
            v.setVisible(true);
            this.dispose();
        } catch (SQLException | NoSuchAlgorithmException | InvalidKeySpecException ex) {
            Logger.getLogger(VerPerfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_VerDadosActionPerformed

    private void VerDadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VerDadosKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) VerDados.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Premium.requestFocusInWindow();
    }//GEN-LAST:event_VerDadosKeyPressed

    private void AvaliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvaliarActionPerformed
        AvaliarApp a = new AvaliarApp(l);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AvaliarActionPerformed

    private void AvaliarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AvaliarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Avaliar.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Pagamentos.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Remove.requestFocusInWindow();
    }//GEN-LAST:event_AvaliarKeyPressed

    private void MatriculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculasActionPerformed
        try {
            GerirMatriculas m = new GerirMatriculas(l);
            m.setVisible(true);
            this.dispose();
        } catch (NoSuchAlgorithmException | InvalidKeySpecException | SQLException | UnsupportedEncodingException | NoSuchPaddingException | InvalidKeyException | IllegalBlockSizeException | BadPaddingException ex) {
            Logger.getLogger(VerPerfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MatriculasActionPerformed

    private void MatriculasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_MatriculasKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Matriculas.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Premium.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Pagamentos.requestFocusInWindow();
    }//GEN-LAST:event_MatriculasKeyPressed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        try {
            MainPage m = new MainPage(l);
            m.setTitle();
            m.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(VerPerfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReturnActionPerformed

    private void ReturnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ReturnKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Return.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) Logout.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Remove.requestFocusInWindow();
    }//GEN-LAST:event_ReturnKeyPressed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        Login lo = new Login();
        lo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogoutActionPerformed

    private void LogoutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LogoutKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Logout.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) Return.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Remove.requestFocusInWindow();
    }//GEN-LAST:event_LogoutKeyPressed

    private void PremiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PremiumActionPerformed
        try {
            if(u.checkPremium(l.getUs())) {
                ContaUpgraded c = new ContaUpgraded(l);
                c.setVisible(true);
                this.dispose();
            } else {
                UpgradeConta up = new UpgradeConta(l);
                up.setVisible(true);
                this.dispose();
            }
        } catch (SQLException | NoSuchAlgorithmException | InvalidKeySpecException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PremiumActionPerformed

    private void PremiumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PremiumKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Premium.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_UP) VerDados.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Matriculas.requestFocusInWindow();
    }//GEN-LAST:event_PremiumKeyPressed

    private void PagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagamentosActionPerformed
        try {
            Historicopagamento h = new Historicopagamento(l);
            h.setVisible(true);
            this.dispose();
            // TODO add your handling code here:
        } catch (SQLException | NoSuchAlgorithmException | InvalidKeySpecException ex) {
            Logger.getLogger(VerPerfil.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PagamentosActionPerformed

    private void PagamentosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PagamentosKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Pagamentos.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Matriculas.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_DOWN) Avaliar.requestFocusInWindow();
    }//GEN-LAST:event_PagamentosKeyPressed

    private void RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Ao premir no OK a sua conta é "
      + "removida permanentemente e não pode mais usar a aplicação. Tem a certeza de que quer continuar?", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        if(option == JOptionPane.OK_OPTION){
            try {
                uo.removeUser(l.getUs());
                JOptionPane.showMessageDialog(null, "A conta foi eliminada com sucesso.", "CONTA ELIMINADA", JOptionPane.INFORMATION_MESSAGE);
                Login lo = new Login();
                lo.setVisible(true);
                this.dispose();
            } catch (NoSuchAlgorithmException | InvalidKeySpecException | SQLException ex) {
                Logger.getLogger(VerPerfil.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_RemoveActionPerformed

    private void RemoveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RemoveKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) Remove.doClick();
        if(evt.getKeyCode() == KeyEvent.VK_LEFT) Return.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_RIGHT) Logout.requestFocusInWindow();
        if(evt.getKeyCode() == KeyEvent.VK_UP) Avaliar.requestFocusInWindow();
    }//GEN-LAST:event_RemoveKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Avaliar;
    private javax.swing.JButton Logout;
    private javax.swing.JButton Matriculas;
    private javax.swing.JButton Pagamentos;
    private javax.swing.JButton Premium;
    private javax.swing.JButton Remove;
    private javax.swing.JButton Return;
    private javax.swing.JButton VerDados;
    private javax.swing.JLabel jLabelVerPefil;
    // End of variables declaration//GEN-END:variables
}
